### ISSUE TITLE
[Security] Workflow test.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by igibek** [actioncloud/issue-tracker-action#6]
The workflow test.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by andreasabel** [comment]
@gingerhot This looks like a fun action to try.  
Has the issue been fixed (it is open for almost a year now).
Also, actions are moving to node-16, are you planning to update this?

**Comment by gingerhot** [comment]
> @gingerhot This looks like a fun action to try. Has the issue been fixed (it is open for almost a year now). Also, actions are moving to node-16, are you planning to update this?

@andreasabel Thanks for your remind and advice. I've fixed this and updated node to 16. And PRs are also welcome~
